image: node:16.9.0

pipelines:
  default:
    - step:
        script:
          - cd client
          - npm i
          # Warnings do not prevent a successful build
          - CI=false npm run build
